export const faqCategories = [
  { id: 'all', label: 'All Questions' },
  { id: 'products', label: 'Products' },
  { id: 'pricing', label: 'Pricing' },
  { id: 'orders', label: 'Orders & Delivery' },
  { id: 'membership', label: 'Membership' },
  { id: 'rewards', label: 'Points & Rewards' },
]

export const faqItems = [
  {
    id: 'question-1',
    category: 'products',
    question: 'What is YOUR PRODUCT?',
    answer: 'YOUR PRODUCT is an in-house fragrance brand offering a curated collection of premium-inspired scents for men and women, designed for everyday wear, special occasions, and different personal styles.',
  },
  {
    id: 'question-2',
    category: 'products',
    question: 'Are YOUR PRODUCT fragrances original designer brands?',
    answer: 'No. YOUR PRODUCT fragrances are in-house products with their own product names, branding, and presentation. Some scents may be developed around familiar fragrance profiles, but YOUR PRODUCT is not affiliated with, sponsored by, or endorsed by any third-party designer brand.',
  },
  {
    id: 'question-3',
    category: 'products',
    question: 'How many fragrances are available?',
    answer: 'The collection currently features 20 scents: 10 for Women (W01-W10) and 10 for Men (M01-M10). A standalone Premium Tester Kit is also available.',
  },
  {
    id: 'question-4',
    category: 'products',
    question: 'What is the Premium Tester Kit?',
    answer: 'The Premium Tester Kit is a standalone ₱700 product that includes 20 pcs 5ml assorted testers, ideal for scent sampling before buying full bottles.',
  },
  {
    id: 'question-5',
    category: 'pricing',
    question: 'How much is a regular perfume bottle?',
    answer: 'The regular customer price is ₱349 per bottle.',
  },
  {
    id: 'question-6',
    category: 'pricing',
    question: 'How much is the member or reseller price per bottle?',
    answer: 'Approved members receive tier pricing based on their membership package: Starter ₱245, Builder ₱227, Leader ₱210, and Prestige ₱175 per bottle.',
  },
  {
    id: 'question-7',
    category: 'pricing',
    question: 'Does the Tester Kit get member discounts?',
    answer: 'No. The Premium Tester Kit has a fixed price of ₱700 whether purchased by a regular customer or an approved member.',
  },
  {
    id: 'question-8',
    category: 'membership',
    question: 'How do I become a member?',
    answer: 'Choose a membership package, create an account, submit the required payment proof, and wait for admin approval. Membership becomes active only after admin approval.',
  },
  {
    id: 'question-9',
    category: 'membership',
    question: 'What membership packages are available?',
    answer: 'Available packages include Starter ₱1,000, Builder ₱5,000, Leader ₱10,000, and Prestige ₱50,000. Each package has its own inclusions and bottle discount tier.',
  },
  {
    id: 'question-10',
    category: 'membership',
    question: 'What is included in the Starter package?',
    answer: 'Starter has two options: Option A includes 4 assorted 60ml bottles. Option B includes 1 Tester Kit plus 2 assorted 60ml bottles. Both provide business access after approval.',
  },
  {
    id: 'question-11',
    category: 'orders',
    question: 'How can I place an order?',
    answer: 'Customers can add products to cart, create or log in to an account, proceed to checkout, and submit payment proof for admin review.',
  },
  {
    id: 'question-12',
    category: 'orders',
    question: 'Can guests add products to cart?',
    answer: 'Yes. Guests may browse and add products to cart, but an account is required before completing checkout and submitting payment proof.',
  },
  {
    id: 'question-13',
    category: 'orders',
    question: 'What payment methods do you accept?',
    answer: 'Available payment instructions are shown during checkout. Orders are reviewed manually after payment proof is submitted.',
  },
  {
    id: 'question-14',
    category: 'orders',
    question: 'How long does delivery take?',
    answer: "Estimated delivery time depends on the customer's location, courier availability, order volume, and other logistics factors. Applicable delivery information will be confirmed during order processing.",
  },
  {
    id: 'question-15',
    category: 'orders',
    question: 'Can I change or cancel my order?',
    answer: 'Order changes or cancellations may be requested before the order is processed for shipment. Once an order has been dispatched, cancellation may no longer be available.',
  },
  {
    id: 'question-16',
    category: 'orders',
    question: 'What if I receive a damaged or incorrect item?',
    answer: 'Contact YOUR PRODUCT customer support as soon as possible and provide your order details plus clear photos or video of the package and item received so the concern can be reviewed.',
  },
  {
    id: 'question-17',
    category: 'rewards',
    question: 'Who can earn points?',
    answer: 'Only active members can earn points. Free customers do not earn points from product orders.',
  },
  {
    id: 'question-18',
    category: 'rewards',
    question: 'How are points earned?',
    answer: 'Approved membership packages earn points after admin approval. Active members also earn 5 points per perfume bottle and 10 points per tester kit after product order approval.',
  },
  {
    id: 'question-19',
    category: 'rewards',
    question: 'Can I request rewards using my points?',
    answer: 'Members can view reward milestones in the Points & Rewards page. Reward request approval and point deduction are subject to official qualification, mechanics, eligibility, and admin review.',
  },
  {
    id: 'question-20',
    category: 'products',
    question: 'Is the perfume long-lasting?',
    answer: 'Fragrance longevity can vary depending on skin type, application, weather, activity, and storage conditions. YOUR PRODUCT is designed to provide a pleasant fragrance experience, but longevity may differ from person to person.',
  },
  {
    id: 'question-21',
    category: 'products',
    question: 'How should I store my perfume?',
    answer: 'Store perfume in a cool, dry place away from direct sunlight, excessive heat, and extreme temperature changes. Keep the bottle properly closed when not in use.',
  },
  {
    id: 'question-22',
    category: 'products',
    question: 'Where can I get official information about YOUR PRODUCT?',
    answer: 'For official product information, pricing, promotions, membership policies, reward rules, and announcements, refer only to the official YOUR PRODUCT website and authorized company channels.',
  },
]